services:
  control-plane:
    build: .
    image: control-plane-backend:latest
    container_name: backend-app
    network_mode: host
    volumes:
      - ./data:/app/data
      - /home/ubuntu/.kube/config:/home/node/.kube/config:ro
      - ./.env:/app/.env:ro
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
